banner: 
  charset: UTF-8
  location: banner.txt
logging:
  file: myapp.log
server:
  port: 8081

spring:
  redis:
    database: 0
    host: localhost
    password: j789456123
    pool:
      max-active: 10
      max-idle: 10
    
  mustache:
    enabled: true
    
  mvc:
    date-format: 'dd/MM/yyyy'
     
Pupil: 
    name: Pupil
    age: 8
CollegeStudent: 
    name: CollegeStudent
    age: 18
      